# Generated by Django 3.0.2 on 2020-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='composition_file',
            field=models.FileField(default='None', max_length=500, upload_to=' '),
        ),
        migrations.AlterField(
            model_name='score',
            name='pdf_file',
            field=models.FileField(default='None', max_length=100000, upload_to=' '),
        ),
    ]
