# Generated by Django 3.0.2 on 2020-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_auto_20200312_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='composition_file',
            field=models.FileField(default='None', max_length=500, upload_to='composition/'),
        ),
        migrations.AlterField(
            model_name='score',
            name='music_file',
            field=models.FileField(default='None', max_length=10000, upload_to='midi/'),
        ),
        migrations.AlterField(
            model_name='score',
            name='pdf_file',
            field=models.FileField(default='None', max_length=100000, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_file',
            field=models.FileField(max_length=300, upload_to='lilypond/'),
        ),
    ]
