# Generated by Django 3.0.2 on 2020-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_auto_20200312_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='composition_file',
            field=models.FileField(default='None', max_length=1000000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='music_file',
            field=models.FileField(default='None', max_length=10000000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='pdf_file',
            field=models.FileField(default='None', max_length=100000000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_file',
            field=models.FileField(max_length=1000000, upload_to=''),
        ),
    ]
