# Generated by Django 3.0.2 on 2020-03-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_auto_20200312_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='pdf_file',
            field=models.FileField(default='None', max_length=100000000, upload_to='pdfs/'),
        ),
    ]
